# Generated by Django 4.1 on 2023-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="phone", field=models.BigIntegerField(),
        ),
    ]
